# Generated by Django 5.2.13 on 2026-04-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_company_size_company_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
