# Generated by Django 5.2.13 on 2026-04-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailtemplate_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='total_invalid',
            field=models.IntegerField(default=0),
        ),
    ]
