# Generated by Django 5.2.13 on 2026-04-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailcampaign_total_invalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_email_invalid',
            field=models.BooleanField(default=False),
        ),
    ]
