# Generated by Django 5.2.13 on 2026-06-09 01:00

from django.db import migrations
from django.contrib.auth.hashers import make_password

def seed_rbac_and_admin(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Role = apps.get_model('core', 'Role')
    Permission = apps.get_model('core', 'Permission')
    RolePermission = apps.get_model('core', 'RolePermission')
    UserRole = apps.get_model('core', 'UserRole')

    # 1. Create default roles
    roles = ['Super Admin', 'Admin', 'Moderator', 'Premium User', 'User', 'Guest']
    role_objs = {}
    for r_name in roles:
        role_objs[r_name], _ = Role.objects.get_or_create(name=r_name)

    # 2. Create default permissions
    perms_list = [
        'USER_MANAGEMENT', 'JOB_MANAGEMENT', 'TASK_MANAGEMENT', 'ANALYTICS_ACCESS',
        'AI_INSIGHTS', 'BEHAVIOR_TRACKING', 'SYSTEM_CONTROL', 'SECURITY_CONTROL',
        'EMAIL_CAMPAIGNS'
    ]
    perm_objs = {}
    for p_name in perms_list:
        perm_objs[p_name], _ = Permission.objects.get_or_create(name=p_name)

    # 3. Associate permissions to roles
    # Super Admin gets all permissions
    super_admin = role_objs['Super Admin']
    for p in perm_objs.values():
        RolePermission.objects.get_or_create(role=super_admin, permission=p)

    # User gets JOB_MANAGEMENT, TASK_MANAGEMENT, ANALYTICS_ACCESS
    user_role = role_objs['User']
    basic_perms = [perm_objs[name] for name in ['JOB_MANAGEMENT', 'TASK_MANAGEMENT', 'ANALYTICS_ACCESS']]
    for p in basic_perms:
        RolePermission.objects.get_or_create(role=user_role, permission=p)

    # Admin gets all except BEHAVIOR_TRACKING, SECURITY_CONTROL
    admin_role = role_objs['Admin']
    admin_perms = [
        p for name, p in perm_objs.items()
        if name not in ['BEHAVIOR_TRACKING', 'SECURITY_CONTROL']
    ]
    for p in admin_perms:
        RolePermission.objects.get_or_create(role=admin_role, permission=p)

    # 4. Create the super admin user
    username = 'admin'
    email = 'admin@example.com'
    if not User.objects.filter(username=username).exists():
        admin_user = User.objects.create(
            username=username,
            email=email,
            password=make_password('admin123'),
            is_superuser=True,
            is_staff=True,
            role='Super Admin'
        )
        UserRole.objects.get_or_create(user=admin_user, role=super_admin)

def remove_rbac_and_admin(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Role = apps.get_model('core', 'Role')
    Permission = apps.get_model('core', 'Permission')
    RolePermission = apps.get_model('core', 'RolePermission')
    UserRole = apps.get_model('core', 'UserRole')

    # Delete the admin user
    User.objects.filter(username='admin').delete()
    
    # Delete UserRole mapping
    UserRole.objects.all().delete()
    
    # Delete RolePermission mapping
    RolePermission.objects.all().delete()
    
    # Delete permissions and roles
    Permission.objects.all().delete()
    Role.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_is_email_invalid'),
    ]

    operations = [
        migrations.RunPython(seed_rbac_and_admin, reverse_code=remove_rbac_and_admin),
    ]
